export const goalVaultAbi = [
  {
    type: "function",
    stateMutability: "view",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "asset",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "targetAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "unlockAt",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "ruleType",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "cooldownDuration",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "guardian",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "unlockRequestedAt",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "guardianDecision",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "guardianDecisionAt",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalDeposited",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalWithdrawn",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getSummary",
    inputs: [],
    outputs: [
      { name: "vaultOwner", type: "address" },
      { name: "vaultAsset", type: "address" },
      { name: "vaultTargetAmount", type: "uint256" },
      { name: "vaultUnlockAt", type: "uint64" },
      { name: "vaultTotalDeposited", type: "uint256" },
      { name: "vaultTotalWithdrawn", type: "uint256" },
      { name: "vaultBalance", type: "uint256" },
      { name: "vaultIsUnlocked", type: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getRuleState",
    inputs: [],
    outputs: [
      { name: "vaultRuleType", type: "uint8" },
      { name: "vaultUnlockAt", type: "uint64" },
      { name: "vaultCooldownDuration", type: "uint64" },
      { name: "vaultGuardian", type: "address" },
      { name: "vaultUnlockRequestedAt", type: "uint64" },
      { name: "vaultGuardianDecision", type: "uint8" },
      { name: "vaultGuardianDecisionAt", type: "uint64" },
      { name: "vaultUnlockEligibleAt", type: "uint64" },
      { name: "vaultWithdrawalEligible", type: "bool" },
    ],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "deposit",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "requestUnlock",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "cancelUnlockRequest",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "approveUnlock",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "rejectUnlock",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    stateMutability: "nonpayable",
    name: "withdraw",
    inputs: [
      { name: "amount", type: "uint256" },
      { name: "to", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "event",
    name: "Deposited",
    inputs: [
      { indexed: true, name: "from", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { indexed: true, name: "to", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "UnlockRequested",
    inputs: [
      { indexed: true, name: "requestedBy", type: "address" },
      { indexed: true, name: "ruleType", type: "uint8" },
      { indexed: false, name: "availableAt", type: "uint256" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "UnlockCanceled",
    inputs: [
      { indexed: true, name: "canceledBy", type: "address" },
      { indexed: true, name: "ruleType", type: "uint8" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "GuardianApproved",
    inputs: [
      { indexed: true, name: "guardian", type: "address" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "GuardianRejected",
    inputs: [
      { indexed: true, name: "guardian", type: "address" },
      { indexed: false, name: "timestamp", type: "uint256" },
    ],
  },
] as const;
