export const goalVaultAbi = [
  {
    type: "function",
    stateMutability: "view",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "asset",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "targetAmount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "unlockAt",
    inputs: [],
    outputs: [{ name: "", type: "uint64" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalDeposited",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "totalWithdrawn",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    stateMutability: "view",
    name: "getSummary",
    inputs: [],
    outputs: [
      { name: "vaultOwner", type: "address" },
      { name: "vaultAsset", type: "address" },
      { name: "vaultTargetAmount", type: "uint256" },
      { name: "vaultUnlockAt", type: "uint64" },
      { name: "vaultTotalDeposited", type: "uint256" },
      { name: "vaultTotalWithdrawn", type: "uint256" },
      { name: "vaultBalance", type: "uint256" },
      { name: "vaultIsUnlocked", type: "bool" },
    ],
  },
] as const;
